version: '3'
services:
  filter-service:
    build: ./randomtext-service
    ports:
     - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - ENVIRONMENT=qa
  mongo:
    image: "mongo:latest"
    container_name: mongo